# Read the documentation: https://symfony.com/doc/master/bundles/FOSRestBundle/index.html
fos_rest:
    allowed_methods_listener:  true
    body_converter:
        enabled: true
        validate: true
        validation_errors_argument: validationErrors # This is the default value
    view:
        view_response_listener: force
        formats:
            json: true
    exception:
        enabled: true
    format_listener:
        rules:
            - { path: ^/api, priorities: ['json'], fallback_format: json, prefer_extension: false }
            - { path: '^/', priorities: ['text/html', '*/*'], fallback_format: html, prefer_extension: true }

