# Template for Apple M1 machines
# Turn on this feature https://www.docker.com/blog/speed-boost-achievement-unlocked-on-docker-desktop-4-6-for-mac/
version: '3.9'
services:

    mysql:
        image: arm64v8/mysql
