version: '3.9'
services:
    redis:
        container_name: redis
        image: redis:latest
        restart: always
        networks:
            - symfony

    mysql: # debian
        container_name: mysql
        image: mysql:8
        command: --default-authentication-plugin=mysql_native_password
        environment:
            MYSQL_DATABASE: symfony_lts_playground
            MYSQL_ROOT_PASSWORD: root
            MYSQL_ALLOW_EMPTY_PASSWORD: 1
        restart: always
        volumes:
            - ./docker/mysql/scripts:/docker-entrypoint-initdb.d
        networks:
            - symfony
        ports:
            - "13306:3306"

    php: # debian
        container_name: php
        build:
            context: ./docker/php-apache-dev
        networks:
            - symfony
        ports:
            - "8000:80"
        volumes:
            - .:/var/www
            - ./var/log:/var/www/var/log
        extra_hosts:
            - "host.docker.internal:host-gateway"

    mailhog:
        container_name: mailhog
        image: mailhog/mailhog
        logging:
            driver: 'none'  # disable saving logs
        networks:
            - symfony
        ports:
            - "1025:1025" # smtp server
            - "8025:8025" # web UI

networks:
    symfony:
        driver: bridge
